# Generated by Django 3.2.9 on 2022-01-09 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_remove_user_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
