# Generated by Django 3.2.11 on 2022-02-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('s_and_p_500', models.FloatField()),
                ('nasdaq', models.FloatField()),
                ('djia', models.FloatField()),
            ],
        ),
    ]
