# Generated by Django 3.2.11 on 2022-05-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_riskassessmentscore_portfolio_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('s_and_p_500', models.JSONField()),
                ('nasdaq', models.JSONField()),
                ('djia', models.JSONField()),
            ],
        ),
    ]
