# Generated by Django 3.2.11 on 2022-05-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_stockdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutualFundData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('vanguard', models.JSONField()),
                ('fidelity', models.JSONField()),
                ('schwab', models.JSONField()),
            ],
        ),
    ]
