# Generated by Django 3.2.11 on 2022-05-12 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_mutualfunddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskassessmentscore',
            name='portfolio_amount',
            field=models.FloatField(),
        ),
    ]
