# Generated by Django 3.2.11 on 2022-05-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_alter_riskassessmentscore_portfolio_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchMarkStockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('s_and_p_500_benchmark', models.JSONField()),
            ],
        ),
    ]
