# Generated by Django 3.2.11 on 2022-05-21 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0013_benchmarkstockdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_discrete_port', models.JSONField()),
                ('stock_port', models.JSONField()),
                ('mf_discrete_port', models.JSONField()),
                ('mf_port', models.JSONField()),
                ('crypto_discrete_port', models.JSONField()),
                ('crypto_port', models.JSONField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
