# Generated by Django 3.2.11 on 2022-05-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='crypto_discrete_port',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='crypto_port',
            field=models.JSONField(default=None),
        ),
    ]
