# Generated by Django 3.2.11 on 2022-05-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0015_auto_20220521_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='crypto_discrete_port',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='crypto_port',
            field=models.JSONField(null=True),
        ),
    ]
