# Generated by Django 3.2.11 on 2022-05-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0016_auto_20220521_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='crypto_breakdown',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='mf_breakdown',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='stock_breakdown',
            field=models.FloatField(null=True),
        ),
    ]
