# Generated by Django 3.2.11 on 2022-06-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0018_cryptodata'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='total_crypto_amount_in_dollars',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='total_mf_amount_in_dollars',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='total_stock_amount_in_dollars',
            field=models.FloatField(null=True),
        ),
    ]
