apiVersion: apps/v1
kind: Deployment
metadata:
  name: tradepro-reimagined-web-deployment
  labels:
    app: tradepro-reimagined-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tradepro-reimagined-web-deployment
  template:
    metadata:
      labels:
        app: tradepro-reimagined-web-deployment
    spec:
      containers:
      - name: tradepro-reimagined-web
        image: registry.digitalocean.com/tradepro-reimagined-k8s/tradepro-reimagined-web:latest
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: tradepro-reimagined-web-prod-env
        env:
          - name: PORT
            value: "8002"
        ports:
        - containerPort: 8002
      imagePullSecrets:
        - name: tradepro-reimagined-k8s


---
apiVersion: v1
kind: Service
metadata:
  name: tradepro-reimagined-web-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8002
  selector:
    app: tradepro-reimagined-web-deployment