name: Build Docker Container & Push to DO Registry

on:
  workflow_call:
  workflow_dispatch:
  
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_django_job:
    uses: steveBaca349934/TradePro_Reimagined/.github/workflows/test-django.yaml@master
  build:

    runs-on: ubuntu-latest
    needs: [test_django_job]

    env:
      DJANGO_SECRET_KEY: test-key-not-good

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_API_TOKEN_KEY }}
    - name: Login to DO Container Registry with short-lived creds
      run: doctl registry login --expiry-seconds 1200
    - name: Build container image
      working-directory: ./TradePro_Reimagined
      run: |
        docker build -f Dockerfile \
          -t registry.digitalocean.com/tradepro-reimagined-k8s/tradepro-reimagined-web:latest \
          -t registry.digitalocean.com/tradepro-reimagined-k8s/tradepro-reimagined-web:${GITHUB_SHA::7} \
          .
    - name: Push image
      run: |
        docker push registry.digitalocean.com/tradepro-reimagined-k8s/tradepro-reimagined-web --all-tags


      

